### ISSUE TITLE
Code to load config

### ISSUE THREAD

**Issue by xXNiceYT** [BajanVlogs/Envoys#10]
Use this code in Main.php

$this->saveResource("Config.yml");
$this->saveResource("Enovys.yml");
$this->saveResource("Items.yml");

**Comment by shavindanagapen** [comment]
@xXNiceAssasinl0 Can you take his um..crates plugin and fix it? I need it ASAP. For some reason again he forgot to do something with the config file for that plugin. His SuperCrates. 

14.01 14:13:35 [Server] Server thread/CRITICAL Could not save Config /plugins/SuperCrates/Items.yml: file_put_contents(/plugins/SuperCrates/Items.yml): failed to open stream: No such file or directory

**Comment by OfficialLilKev** [comment]
Thanks
