### ISSUE TITLE
config not working 

### ISSUE THREAD

**Issue by shavindanagapen** [BajanVlogs/Envoys#11]
14.01 14:13:35 [Server] Server thread/CRITICAL Could not save Config /plugins/Envoys/resources\Envoys.yml: file_put_contents(/plugins/Envoys/resources\Envoys.yml): failed to open stream: No such file or director

**Comment by xXNiceYT** [comment]
I act in movie with your baby sitter

**Comment by shavindanagapen** [comment]
excuse you?

**Comment by xXNiceYT** [comment]
Lol

**Comment by xXNiceYT** [comment]
@CyanCreeperPlayz  I fixed bug redownload
