### ISSUE TITLE
Envoys don't spawn

### ISSUE THREAD

**Issue by austina1212** [BajanVlogs/Envoys#16]
Hello, I use this plugin and envoys do not spawn. There is no errors in console, and I have done /envoy set (I have also checked the envoy.yml and it is in the format of 500, 500, 500 not 500.55342 or some shit)

**Comment by TheMasterDuper** [comment]
This guy did not have his code clean so it has many errors.

**Comment by OfficialLilKev** [comment]
You have to place them down yourself at the position you put in the yml file
