### ISSUE TITLE
Lol

### ISSUE THREAD

**Issue by XFizzer** [BajanVlogs/Envoys#2]
Don't change my messages

**Comment by NFGamerMC** [comment]
DMca him

**Comment by Dragonblitz10** [comment]
@XFizzer the reason he can't finish this is he did not code this at all but copied it from the guy who did not finish it, and claimed credit for it and @NFGamerMC I don't think he can

**Comment by daniktheboss** [comment]
Uh, I coded this and own this plugin. I don't really care if he does it public and takes credit. And this is finished tf you mean 😂

**Comment by xXNiceYT** [comment]
B

**Comment by OfficialLilKev** [comment]
What
