### ISSUE TITLE
Doesn't seem good

### ISSUE THREAD

**Issue by TheAz928** [BajanVlogs/Envoys#3]
I'd advise to not use "unnecessary codes" such as
$player->getPotision()->asVector3();

$player is a position itself, also setting a blocks doesn't full fill envoy needs

**Comment by OfficialLilKev** [comment]
If you would like to make a commit you can.

**Comment by karanpatel567** [comment]
Lol

**Comment by ghost** [comment]
https://www.youtube.com/watch?v=i6TfjyTHmzA

**Comment by OfficialLilKev** [comment]
@FreakingDev add me on discord for we can talk about a paid job KevinVlogs#4751

**Comment by ghost** [comment]
:D
