### ISSUE TITLE
enchants

### ISSUE THREAD

**Issue by XoticRealmsOwnerandDev** [BajanVlogs/Envoys#4]
can you add support for custom enchants and just vanilla enchants

https://github.com/DaPigGuy/PiggyCustomEnchants ce's

**Comment by OfficialLilKev** [comment]
Sure will add this very soon

**Comment by xXNiceYT** [comment]
It so ez

**Comment by OfficialLilKev** [comment]
Then @xXNiceAssasinl0 make a PR then

**Comment by xXNiceYT** [comment]
Okay i will

**Comment by OfficialLilKev** [comment]
I would do it but I'm really busy if you want to take a look at Issue #1 on my TransferUI plugin u can

**Comment by OfficialLilKev** [comment]
@xXNiceAssasinl0

**Comment by xXNiceYT** [comment]
Oh okay

**Comment by xXNiceYT** [comment]
I’ll make my own Envoy plugin

**Comment by OfficialLilKev** [comment]
If you use any of my code please give credits

**Comment by xXNiceYT** [comment]
Sure, I will use some.
