### ISSUE TITLE
No config.yml, no envoys.yml, etc

### ISSUE THREAD

**Issue by Benjiboi6578** [BajanVlogs/Envoys#5]
The plugin  is installable but you can't set envoy. The error "an unknown error occurred while attempting to perform this command" happens when you do /set envoy. This for newest version that was just released.

**Comment by OfficialLilKev** [comment]
just place down the chest and do /whereami then put that down in the envoys.yml please follow my format

**Comment by Benjiboi6578** [comment]
When you install the plug in, there's no envoys.yml. so I can't put the coords

**Comment by xXNiceYT** [comment]
@Benjiboi6578 I fixed bug redownload

**Comment by Benjiboi6578** [comment]
@xXNiceAssasinl0 Thanks for fixing bug.

**Comment by Benjiboi6578** [comment]
@xXNiceAssasinl0 Do you have a server and if you do, do you need staff?

**Comment by xXNiceYT** [comment]
@Benjiboi6578 Nope but I have discord server https://discord.gg/V5CYfWd
