### ISSUE TITLE
Plugin Not Working

### ISSUE THREAD

**Issue by xXNiceYT** [BajanVlogs/Envoys#6]
The Plugin doesn’t put item in chest, and it doesn’t save config. You need resources folder.

**Comment by Benjiboi6578** [comment]
That's what I was telling Bajan yesterday but he closed my issue. XD Also what's the format for putting in the envoy coords. Need to be specific.

**Comment by xXNiceYT** [comment]
Idk

**Comment by ghost** [comment]
Does the plug-in only work .phar?

**Comment by xXNiceYT** [comment]
Nah, The Plugin Doesn’t work this plugin need fix from @Mojang RIP.

**Comment by Benjiboi6578** [comment]
Do you guys use netbeans or eclipse to code?

**Comment by xXNiceYT** [comment]
@Benjiboi6578 I use Phone

**Comment by Benjiboi6578** [comment]
you do?

**Comment by xXNiceYT** [comment]
Ya

**Comment by Benjiboi6578** [comment]
you coded crateui on phone?

**Comment by xXNiceYT** [comment]
Ya

**Comment by Benjiboi6578** [comment]
wow. impressive, teach me. I'm having trouble uploading the files from my netbeans to my server

**Comment by xXNiceYT** [comment]
I broke my mouse

**Comment by Benjiboi6578** [comment]
oh so thats why ur coding on phone. So u usually code on computer.

**Comment by xXNiceYT** [comment]
Ya, so I am stuck with my phone

**Comment by Benjiboi6578** [comment]
so what do you normally use? eclipse or netbeans?

**Comment by xXNiceYT** [comment]
Non of those.

**Comment by Benjiboi6578** [comment]
phpstorm?

**Comment by xXNiceYT** [comment]
Nope

**Comment by Benjiboi6578** [comment]
well then...

**Comment by xXNiceYT** [comment]
visual studio code

**Comment by Benjiboi6578** [comment]
oh. never heard of it

**Comment by OfficialLilKev** [comment]
Plugin should be working now
