### ISSUE TITLE
you should be more carefull

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [BajanVlogs/Envoys#7]
Command, is a mess
Plugin don't load because it cant detect resources, I had to move them manually, then after I set envoys another files appeared, resouces/items.yml as file name.
Plugin need rewrite.

P.s. IS just a chest refill plugin? It just spawn chest and refill it. Chests should vanish and spawn wen  envoys drop.

**Comment by OfficialLilKev** [comment]
Will redo the plugin soon
