### ISSUE TITLE
Plugin config don’t load

### ISSUE THREAD

**Issue by xXNiceYT** [BajanVlogs/Envoys#9]
Title tell you all ;)

**Comment by OfficialLilKev** [comment]
Just copy config from the plugin and remake it on your server

**Comment by xXNiceYT** [comment]
Dude

**Comment by shavindanagapen** [comment]
lol i hate when devs are rude...they think that I know how to develop I am the boss....also with youtubers..im famous now so im not going to reply to my fans...

**Comment by xXNiceYT** [comment]
I’ll fix Envoy

**Comment by shavindanagapen** [comment]
Thanks

**Comment by xXNiceYT** [comment]
You have discord

**Comment by xXNiceYT** [comment]
@CyanCreeperPlayz discord

**Comment by shavindanagapen** [comment]
Yes, here: CyanCreeperPlayz#7788

**Comment by shavindanagapen** [comment]
CyanCreeperPlayz#7788
